name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
     - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        sudo apt-get install -y build-essential openmpi-bin libopenmpi-dev 
    - name: make distcheck
      run: ./autogen.sh
    - name: overlap on CPU
      run:  mpirun -np 4 ./bin/overlapX --dim=2 --ratio=100 --dev=cpu --with-progress=1 --compute-bound=1
